import React, { useState } from 'react';
import { View, ScrollView, Text, StyleSheet, TouchableOpacity } from 'react-native';
import Checkbox from 'expo-checkbox';

const AgreementScreen = ({ navigation }) => {
  const [agreement1Accepted, setAgreement1Accepted] = useState(false);
  const [agreement2Accepted, setAgreement2Accepted] = useState(false);

  return (
    <ScrollView contentContainerStyle={styles.container}>
      {/* Agreement 1 */}
      <Text style={styles.title}>User Agreement 1</Text>
      <ScrollView style={styles.textContainer} nestedScrollEnabled={true}>
        <Text style={styles.text}>
          This User Agreement is between you (‘customer’) and Xecurify Inc (DBA miniOrange Security Software
          Private Limited).
          {'\n\n'}
          PLEASE READ THIS AGREEMENT BEFORE USING ANY Xecurify SOFTWARE OR SERVICES. BY
          DOWNLOADING, INSTALLING OR USING ANY Xecurify SOFTWARE OR SERVICES YOU (“the
          Customer”) SIGNIFY ACCEPTANCE OF AND AGREE TO THE TERMS AND CONDITIONS OF THIS
          AGREEMENT.
          {'\n\n'}
          “Customer” or “you” agree to the terms of this Agreement. If you are entering into this Agreement
          on behalf of a company or other legal entity, you represent that you have the authority to bind such
          entity and its Affiliates to this Agreement. If you do not have such authority, or if you do not agree
          with these terms and conditions, you must not accept this Agreement and may not use the Service.
          {'\n\n'}
          This Agreement is effective as of that date that you accept it. Customer and Xecurify hereby agree as
          follows:
          {'\n\n'}
          1. Definitions
          {'\n'}
          1.1. “Affiliate” means any entity that directly or indirectly controls, is controlled by, or is under
          common control with the Customer entity signing this Agreement. "Control," for purposes of this
          definition, means direct or indirect ownership or control of more than 50% of the voting interests of
          the subject entity.
          {'\n\n'}
          1.2. “Free Trial Service” means any Xecurify service or functionality that may be made available by
          Xecurify to Customer to try at Customer’s option, at no additional charge, and which is clearly
          designated as “beta,” “trial,” “non-GA,” “pilot,” “developer preview,” “non-production,” “free trial,”
          “evaluation,” or by a similar designation.
        </Text>
      </ScrollView>
      <View style={styles.checkboxContainer}>
        <Checkbox
          value={agreement1Accepted}
          onValueChange={setAgreement1Accepted}
          color={agreement1Accepted ? '#4630EB' : undefined}
        />
        <Text style={styles.label}>I agree to terms 1</Text>
      </View>

      {/* Agreement 2 */}
      <Text style={styles.title}>User Agreement 2</Text>
      <ScrollView style={styles.textContainer} nestedScrollEnabled={true}>
        <Text style={styles.text}>
          This user agreement (“User Agreement”) is an electronic record in terms of the Information Technology Act,
          2000 as amended from time to time ("Act") and rules thereunder as applicable and the amended
          provisions pertaining to electronic records in various statutes as amended by the Act.
          {'\n\n'}
          This user agreement is generated by a computer system and does not require any physical or digital signatures.
          {'\n\n'}
          This user agreement is published in accordance with the provisions of Rule 3 (1) of the Information
          Technology (Intermediaries Guidelines) Rules, 2011 that require publishing the rules and regulations,
          privacy policy and terms and conditions for access and/or usage of this website/service
          ("Website/Service").
          {'\n\n'}
          In this User Agreement, the following terms shall have the meaning as ascribed to them below:
          {'\n'}
          "User" refers to you, the person visiting, accessing and/or using the Website by means of any
          communication device.
          {'\n'}
          "Viacom18" refers to Viacom 18 Media Private Limited, a company incorporated under the Indian
          Companies Act, 1956, having its registered office at Zion Biz World, Mumbai, India.
          {'\n\n'}
          This is a legal and binding agreement between You and the Company and states the terms that govern Your use of the Website.
          By accessing this Website, You consent, agree and undertake to abide by the User Agreement.
          assume that You have been authorized by Your parent/legal guardian and they will be
          responsible for ensuring that such use and access of the Website by You must be in accordance
          with these User Agreement and the Privacy Policy. Your parent/legal guardian understands and
          agrees to the aforesaid terms on Your behalf. If You are under the Age of Majority at the time of
          accessing and/or using the Website, Your access and usage of the Website shall be deemed to
          be subject to parental/legal guardian consent and under parental/legal guardian’s guidance at
          all times. You and Your parents/legal guardians confirm that the Website is offered to You for
          Your enjoyment and these User Agreement shall constitute a legally binding user agreement
          between the Company and Your parents/guardians who are contracting on behalf of You.
          Where Users are below the Age of Majority, all references to "User", "You" and "Your" shall
          mean and include You and Your parents/ legal guardians acting for and on Your behalf for Your
          benefit.
          1.3. Some content offered on the Website may not be suitable for some Users and therefore viewer
          discretion/parental discretion is advised. Also, some content offered on the Website may not be
          appropriate for viewership by persons below the Age of Majority. If You are under the Age of
          Majority, You may view the content only with prior consent of Your parents/legal guardians.
          Parents/legal guardians are advised to exercise discretion before allowing their children
          and/or wards to access this Website and/or any Material (as defined later). Your access to and
          use of the Website is subject to these User Agreement, Privacy Policy and all applicable laws,
          rules, and regulations in India.
          1.4. The Company grants You a personal, revocable, non-•-exclusive, non-•-transferable right to access
          and use the Website, for non-•-commercial use only and private viewing only, in accordance
          with these User Agreement. These User Agreement, govern Your access of the Website and any
          data, message, text, image, audio, sound, voice, codes, computer programmes, software,
          database, micro film, video, information, content, etc. that You host, publish, share, transact,
          display and/or upload.
          1.5. Please note that the availability of the Website in Your jurisdiction, and Your ability to access the
          Website is subject to the Company’s sole discretion. The Company may at its sole discretion restrict
          the Website from being accessed in certain geographical locations. You undertake that Your access
          of the Website shall be in compliance with all applicable laws (as amended from time-•-to-•-time).
          You understand that Your access of the Website and its contents may vary depending upon Your
          jurisdiction, device specifications, internet connection, etc. You acknowledge and agree that We will
          provide You only access to the Website and that You will be solely responsible for all equipment as
          may be necessary for You to access the internet, mobile and/or other connection, operator and
          service fees associated with Your access, etc.

        </Text>
      </ScrollView>
      <View style={styles.checkboxContainer}>
        <Checkbox
          value={agreement2Accepted}
          onValueChange={setAgreement2Accepted}
          color={agreement2Accepted ? '#4630EB' : undefined}
        />
        <Text style={styles.label}>I agree to terms 2</Text>
      </View>

      {/* Next Button */}
      <TouchableOpacity
        style={[styles.button, !agreement1Accepted || !agreement2Accepted ? styles.disabledButton : null]}
        disabled={!agreement1Accepted || !agreement2Accepted}
        onPress={() => navigation.navigate('CaseRecord')}
      >
        <Text style={styles.buttonText}>Next</Text>
      </TouchableOpacity>
    </ScrollView>
  );
};

const styles = StyleSheet.create({
  container: {
    padding: 20,
    paddingBottom: 40,
  },
  title: {
    fontSize: 18,
    fontWeight: 'bold',
    marginVertical: 10,
  },
  textContainer: {
    height: 300,
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 5,
    padding: 10,
    marginBottom: 10,
    backgroundColor: '#f9f9f9',
  },
  text: {
    fontSize: 14,
    color: '#333',
    textAlign: 'justify',
    lineHeight: 24, // Adjust this value as needed
  },
  checkboxContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  label: {
    marginLeft: 8,
    fontSize: 16,
  },
  button: {
    backgroundColor: '#007AFF',
    padding: 15,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 20,
  },
  disabledButton: {
    backgroundColor: '#ccc',
  },
  buttonText: {
    color: 'white',
    textAlign: 'center',
    fontSize: 20,
    fontWeight: '700',
  },
});

export default AgreementScreen;
